export const TimeLineData = [
    { 
        id: 1,
        title: "Titre",
        location: "Paris, France",
        description: "Ma description blabla...",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'work', 
    },
    { 
        id: 2,
        title: "Titre 2",
        location: "Paris, France",
        description: "Ma description blabla...",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'work', 
    },
    { 
        id: 3,
        title: "Titre 3",
        location: "Paris, France",
        description: "Ma description blabla...",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'school', 
    },
    { 
        id: 4,
        title: "Titre 4",
        location: "Paris, France",
        description: "Ma description blabla...",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'work', 
    },
    { 
        id: 5,
        title: "Titre 5",
        location: "Paris, France",
        description: "Ma description blabla...",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'school', 
    },
  ];